import { INoteRepository } from '../../../domain/note/note.repository.interface';
import { Note } from '../../../domain/note/note.entity';

export class CreateNoteUseCase {
    constructor(private noteRepository: INoteRepository) { }

    async execute(userId: string, title: string, content: string): Promise<Note> {
        const note = new Note(
            '', // ID generated by DB
            userId,
            title,
            content,
            false,
            false,
            false,
            new Date(),
            new Date(),
            null
        );
        return this.noteRepository.create(note);
    }
}
